# Generated by Django 3.1.7 on 2021-03-29 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kayit_islemleri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kayit_Turu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='okul',
            name='kayit_turu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kayit_islemleri.kayit_turu', verbose_name='Kayit Turu'),
        ),
    ]
