# Generated by Django 3.1.7 on 2021-03-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Okul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sehir', models.CharField(max_length=50, verbose_name='Sehir')),
                ('kayit_turu', models.CharField(max_length=50, verbose_name='Kayit Turu')),
                ('isim_soyisim', models.CharField(max_length=50, verbose_name='Isim Soyisim')),
                ('telefon', models.BigIntegerField(verbose_name='Telefon')),
            ],
            options={
                'db_table': 'kayit_islemleri_okul',
            },
        ),
    ]
